name: Chain Add
description: Add a chain to the blacklist
title: "[Chain add]: "
body: 
  - type: input
    id: chain-id
    attributes:
      label: Chain ID
      description: Enter the chain id of the chain in question
      placeholder: e.g. fakechain-3
    validations:
      required: true
  - type: textarea
    id: user-note    
    attributes:
      label: Notes
      description: Why is this chain malicious? 
      placeholder: e.g. mpersonates a legit chain
    validations:
      required: true
  - type: dropdown
    id: threat-level
    attributes:
      label: Threat level
      description: What do you consider this chain's threat-level to be
      options: 
        - 1 (Low) A warning should be displayed when interacting
        - 2 (Medium) Chain must be explicitly enabled in settings before interacting
        - 3 (High) Chain should not be allowed under any circumstances
    validations:
      required: true

