name: Issue-to-PR
on:
  issues:
    types:
      - opened
      - reopened
jobs:
  issue_to_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: node index.js
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_REPO: ${{ github.repository }}
        NUMBER: ${{ github.event.issue.number }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: |
            Automated commit: ${{github.event.issue.title}}

            ${{github.event.issue.body}}
        title: "Automated PR ${{github.event.issue.title}}"
        body: |
            Closes #${{ github.event.issue.number }}